"""Loughran-McDonald Financial Sentiment Word Lists.

Comprehensive word lists from the Loughran-McDonald financial sentiment dictionary,
widely used in financial NLP research for analyzing corporate disclosures.
"""

POSITIVE_WORDS = {
    "accomplish", "accomplished", "accomplishes", "accomplishing", "accomplishment",
    "achieve", "achieved", "achievement", "achievements", "achieves", "achieving",
    "advance", "advanced", "advancement", "advancements", "advances", "advancing",
    "advantage", "advantaged", "advantageous", "advantages", "assure", "assured",
    "attain", "attained", "attainment", "attains", "attractive",
    "benefit", "benefited", "beneficial", "benefiting", "benefits", "best",
    "better", "bolster", "bolstered", "bolstering", "bolsters", "boost",
    "boosted", "boosting", "boosts", "breakthrough", "breakthroughs",
    "collaborate", "collaborated", "collaborating", "collaboration", "collaborations",
    "commend", "commended", "competent", "complement", "complementary",
    "compliment", "complimentary", "confident", "constructive", "cooperate",
    "creative", "creativity",
    "delight", "delighted", "deliver", "delivered", "delivering", "delivers",
    "dependable", "desirable", "diligent", "distinction", "distinctive",
    "diversified", "diversify", "diversifying",
    "earn", "earned", "earning", "earnings", "easier", "easy", "effective",
    "effectively", "effectiveness", "efficiencies", "efficiency", "efficient",
    "efficiently", "empower", "empowered", "empowering", "enable", "enabled",
    "enabling", "encourage", "encouraged", "encouraging", "endorse", "endorsed",
    "enhance", "enhanced", "enhancement", "enhancements", "enhances", "enhancing",
    "enjoy", "enjoyed", "enjoying", "enjoys", "enthusiasm", "enthusiastic",
    "exceed", "exceeded", "exceeding", "exceeds", "excel", "excelled",
    "excellent", "excels", "exceptional", "exceptionally", "excited",
    "excitement", "exciting", "exclusive", "exemplary", "expand", "expanded",
    "expanding", "expansion", "expansions", "expands",
    "favorable", "favorably", "gain", "gained", "gaining", "gains",
    "good", "great", "greater", "greatest", "grow", "growing", "grown",
    "grows", "growth",
    "happily", "happy", "highest", "honor", "honored",
    "ideal", "imagination", "impressive", "improve", "improved", "improvement",
    "improvements", "improves", "improving", "incredible", "incredibly",
    "influential", "informative", "ingenuity", "innovate", "innovated",
    "innovating", "innovation", "innovations", "innovative", "insight",
    "insightful", "insights", "inspiration", "inspire", "inspired",
    "integrity",
    "leader", "leaders", "leadership", "leading", "leverage", "leveraged",
    "leveraging",
    "maximize", "maximized", "maximizes", "maximizing", "merit",
    "meritorious", "milestone", "milestones", "momentum",
    "noteworthy",
    "opportunities", "opportunity", "optimal", "optimism", "optimistic",
    "optimize", "optimized", "optimizing", "outpace", "outpaced",
    "outperform", "outperformance", "outperformed", "outperforming",
    "outperforms", "outstanding",
    "pleased", "pleasure", "popular", "popularity", "positive", "positively",
    "proactive", "proactively", "proficiency", "proficient", "profit",
    "profitability", "profitable", "profitably", "profits", "progress",
    "progressed", "progresses", "progressing", "progressive", "prominent",
    "promising", "prosper", "prospered", "prospering", "prosperity",
    "prosperous", "proud", "proudly",
    "rebound", "rebounded", "rebounding", "record", "records", "recover",
    "recovered", "recovering", "recovery", "reliable", "remarkable",
    "remarkably", "resilience", "resilient", "resolve", "resolved",
    "reward", "rewarded", "rewarding", "rewards", "robust",
    "satisfaction", "satisfactory", "satisfied", "satisfy", "satisfying",
    "significantly", "solid", "solution", "solutions", "solve", "solved",
    "solving", "stability", "stabilize", "stabilized", "stabilizing",
    "stable", "strength", "strengthen", "strengthened", "strengthening",
    "strengthens", "strengths", "strong", "stronger", "strongest",
    "succeed", "succeeded", "succeeding", "succeeds", "success",
    "successes", "successful", "successfully", "superior", "surpass",
    "surpassed", "surpasses", "surpassing", "sustainable", "sustain",
    "sustained", "sustaining",
    "thrive", "thrived", "thrives", "thriving", "top", "tops",
    "transform", "transformation", "transformative", "transformed",
    "tremendous", "tremendously", "triumph", "trust", "trusted",
    "unmatched", "unparalleled", "unprecedented", "upgrade", "upgraded",
    "upgrades", "upgrading", "upside",
    "valuable", "value", "versatile", "vibrant", "vigorous", "vigor",
    "win", "winning", "wins", "won", "world-class", "worthy",
}

NEGATIVE_WORDS = {
    "abandon", "abandoned", "abandoning", "abandonment", "abdicate",
    "aberrant", "aberration", "abuse", "abused", "abuses", "abusing",
    "accident", "accidents", "accuse", "accused", "accuses", "accusing",
    "adulterate", "adulterated", "adulterating", "adulteration",
    "adversarial", "adversary", "adverse", "adversely", "adversity",
    "allegation", "allegations", "allege", "alleged", "allegedly", "alleges",
    "alleging", "annul", "annulled", "annulling", "annuls",
    "breach", "breached", "breaches", "breaching", "break", "breakdown",
    "breakdowns", "burden", "burdened", "burdens", "burdensome",
    "calamity", "cancel", "canceled", "cancellation", "cancellations",
    "cancelled", "cancelling", "challenge", "challenged", "challenges",
    "challenging", "closing", "closure", "closures", "collapse",
    "collapsed", "collapses", "collapsing", "complain", "complained",
    "complaining", "complains", "complaint", "complaints", "concern",
    "concerned", "concerning", "concerns", "condemn", "condemned",
    "condemning", "condemns", "conflict", "conflicts", "confront",
    "confronted", "confronting", "confronts", "contraction", "controversy",
    "controversial", "convict", "convicted", "conviction", "crisis",
    "critical", "critically", "criticism", "criticisms", "criticize",
    "criticized", "criticizes", "criticizing", "curtail", "curtailed",
    "curtailing", "curtailment", "curtails", "cut", "cutback", "cutbacks",
    "damage", "damaged", "damages", "damaging", "danger", "dangerous",
    "dangerously", "dangers", "deadlock", "deadlocked", "deadlocks",
    "death", "deaths", "debarment", "debarred", "debt", "debts",
    "decline", "declined", "declines", "declining", "decrease",
    "decreased", "decreases", "decreasing", "default", "defaulted",
    "defaulting", "defaults", "defeat", "defeated", "defeats",
    "defect", "defective", "defects", "defend", "defendant", "defendants",
    "deficit", "deficits", "defraud", "defrauded", "defrauding",
    "delay", "delayed", "delaying", "delays", "delinquencies",
    "delinquency", "delinquent", "delist", "delisted", "delisting",
    "denial", "denied", "denies", "denigrate", "deny", "denying",
    "deplete", "depleted", "depleting", "depletion", "depreciation",
    "depressed", "depresses", "depressing", "depression", "deprivation",
    "derelict", "dereliction", "deteriorate", "deteriorated",
    "deteriorates", "deteriorating", "deterioration", "detract",
    "detracted", "detracting", "detracts", "detriment", "detrimental",
    "devalue", "devalued", "devalues", "devaluing", "devastate",
    "devastated", "devastating", "devastation", "diminish", "diminished",
    "diminishes", "diminishing", "disadvantage", "disadvantaged",
    "disadvantages", "disadvantageous", "disappoint", "disappointed",
    "disappointing", "disappointingly", "disappointment", "disappointments",
    "disappoints", "disaster", "disasters", "disastrous", "disclaim",
    "disclaimed", "disclaimer", "disclaimers", "disclaiming", "disclaims",
    "disclose", "disclosed", "discloses", "disclosing", "disclosure",
    "disclosures", "discontinue", "discontinued", "discontinues",
    "discontinuing", "discourage", "discouraged", "discourages",
    "discouraging", "discrepancy", "discrimination", "disfavor",
    "disfavored", "disfavoring", "disfavors", "dismal", "dismally",
    "dismiss", "dismissal", "dismissals", "dismissed", "dismisses",
    "dismissing", "displace", "displaced", "displaces", "displacing",
    "disposal", "dispose", "disposed", "disposes", "disposing",
    "dispute", "disputed", "disputes", "disputing", "disqualification",
    "disqualified", "disqualify", "disqualifying", "disregard",
    "disregarded", "disregarding", "disregards", "disrupt", "disrupted",
    "disrupting", "disruption", "disruptions", "disruptive", "disrupts",
    "dissatisfaction", "dissatisfied", "dissolution", "dissolve",
    "distort", "distorted", "distorting", "distortion", "distortions",
    "distress", "distressed", "disturb", "disturbance", "disturbed",
    "disturbing", "divest", "divested", "divesting", "divestiture",
    "divestitures", "divestment", "divests", "downgrade", "downgraded",
    "downgrades", "downgrading", "downturn", "downturns", "downward",
    "drag", "drags", "drop", "dropped", "dropping", "drops",
    "erode", "eroded", "erodes", "eroding", "erosion", "erratic",
    "error", "errors", "escalate", "escalated", "escalates", "escalating",
    "evict", "evicted", "evicting", "eviction", "evictions",
    "exacerbate", "exacerbated", "exacerbates", "exacerbating",
    "excessive", "excessively", "exploit", "exploitation", "exploited",
    "exploiting", "exploits", "expose", "exposed", "exposes", "exposing",
    "exposure", "exposures",
    "fail", "failed", "failing", "fails", "failure", "failures",
    "fallout", "false", "falsely", "falsification", "falsified",
    "falsify", "falsifying", "fatal", "fatalities", "fatality",
    "fault", "faulty", "fear", "fears", "fine", "fined", "fines",
    "fining", "fire", "fired", "firing", "fluctuate", "fluctuated",
    "fluctuates", "fluctuating", "fluctuation", "fluctuations",
    "forbid", "forbidden", "force", "forced", "forcing", "foreclosure",
    "foreclosures", "forfeit", "forfeited", "forfeiting", "forfeits",
    "forfeiture", "forfeitures", "fraud", "frauds", "fraudulent",
    "fraudulently",
    "halt", "halted", "halting", "halts", "hamper", "hampered",
    "hampering", "hampers", "hardship", "hardships", "harm", "harmed",
    "harmful", "harming", "harms", "harsh", "harshly", "hazard",
    "hazardous", "hazards", "hinder", "hindered", "hindering", "hinders",
    "hindrance", "hostile",
    "idle", "idled", "idling", "ignore", "ignored", "ignores", "ignoring",
    "illegal", "illegally", "illicit", "illicitly", "impair", "impaired",
    "impairing", "impairment", "impairments", "impairs", "impasse",
    "impede", "impeded", "impedes", "impeding", "impediment",
    "impediments", "impossible", "improper", "improperly",
    "inability", "inaccessible", "inaccuracy", "inaccurate",
    "inaccurately", "inadequacy", "inadequate", "inadequately",
    "inadvertent", "inadvertently", "inappropriate", "inappropriately",
    "incapable", "incidence", "incident", "incidents", "incompatibility",
    "incompatible", "incompetence", "incompetent", "incomplete",
    "inconsistencies", "inconsistency", "inconsistent", "inconvenience",
    "incorrect", "incorrectly", "ineffective", "ineffectively",
    "inefficiency", "inefficient", "inefficiently", "ineligible",
    "inferior", "inflict", "inflicted", "inflicting", "inflicts",
    "infraction", "infractions", "infringe", "infringed", "infringement",
    "infringements", "infringes", "infringing", "injunction",
    "injunctions", "injure", "injured", "injures", "injuries",
    "injuring", "injury", "insolvent", "instability", "insufficient",
    "insufficiently", "interfere", "interfered", "interference",
    "interferes", "interfering", "interrupt", "interrupted",
    "interrupting", "interruption", "interruptions", "interrupts",
    "investigate", "investigated", "investigates", "investigating",
    "investigation", "investigations",
    "jeopardize", "jeopardized", "jeopardizes", "jeopardizing",
    "lack", "lacked", "lacking", "lacks", "lag", "lagged", "lagging",
    "lags", "lapse", "lapsed", "lapses", "lapsing", "late", "layoff",
    "layoffs", "liability", "liabilities", "liquidate", "liquidated",
    "liquidates", "liquidating", "liquidation", "liquidations",
    "litigation", "litigations", "lose", "loser", "losers", "loses",
    "losing", "loss", "losses", "lost",
    "malfeasance", "malfunction", "malfunctioned", "malfunctioning",
    "malfunctions", "malpractice", "manipulate", "manipulated",
    "manipulates", "manipulating", "manipulation", "manipulations",
    "misappropriate", "misappropriated", "misappropriating",
    "misappropriation", "misconduct", "mishandle", "mishandled",
    "mislead", "misleading", "misleads", "misled", "mismanage",
    "mismanaged", "mismanagement", "misrepresent", "misrepresentation",
    "misrepresentations", "misrepresented", "misrepresenting",
    "misrepresents", "miss", "missed", "misses", "missing",
    "mistake", "mistaken", "mistakenly", "mistakes",
    "negate", "negated", "negates", "negating", "negation", "negative",
    "negatively", "neglect", "neglected", "neglecting", "negligence",
    "negligent", "negligently",
    "obstacle", "obstacles", "obstruct", "obstructed", "obstructing",
    "obstruction", "offend", "offended", "offender", "offenders",
    "offending", "offense", "offenses", "omission", "omissions",
    "omit", "omits", "omitted", "omitting", "onerous", "oppose",
    "opposed", "opposes", "opposing", "opposition", "outage", "outages",
    "overdue", "overload", "overloaded", "overrun", "overruns",
    "oversight",
    "penalty", "penalties", "penalize", "penalized", "penalizes",
    "penalizing", "peril", "perilous", "perils", "perjury",
    "plagiarize", "plagiarized", "plagiarizing", "plummet", "plummeted",
    "plummeting", "plummets", "poor", "poorly", "preclude", "precluded",
    "precludes", "precluding", "prejudice", "prejudiced", "prejudices",
    "prejudicial", "problem", "problematic", "problems", "prohibit",
    "prohibited", "prohibiting", "prohibition", "prohibitions",
    "prohibitive", "prohibitively", "prohibits", "prosecute",
    "prosecuted", "prosecutes", "prosecuting", "prosecution",
    "prosecutions", "protest", "protested", "protesting", "protests",
    "punish", "punished", "punishes", "punishing", "punishment",
    "punishments", "punitive",
    "recess", "recession", "recessionary", "recessions",
    "refuse", "refused", "refuses", "refusing", "reject", "rejected",
    "rejecting", "rejection", "rejections", "rejects", "restrain",
    "restrained", "restraining", "restraint", "restraints", "restrict",
    "restricted", "restricting", "restriction", "restrictions",
    "restrictive", "restricts", "restructure", "restructured",
    "restructures", "restructuring", "restructurings", "retaliate",
    "retaliated", "retaliates", "retaliating", "retaliation",
    "retaliatory", "revoke", "revoked", "revokes", "revoking", "risk",
    "risked", "riskier", "riskiest", "risking", "risks", "risky",
    "sabotage", "sacrifice", "sacrificed", "sacrifices", "sacrificing",
    "sanction", "sanctioned", "sanctioning", "sanctions", "scandal",
    "scandals", "scarcity", "scrutinize", "scrutinized", "scrutinizes",
    "scrutinizing", "scrutiny", "seize", "seized", "seizes", "seizing",
    "seizure", "seizures", "setback", "setbacks", "severe", "severely",
    "severity", "shortage", "shortages", "shortcoming", "shortcomings",
    "shortfall", "shortfalls", "shrink", "shrinkage", "shrinking",
    "shrinks", "shrunk", "shutdown", "shutdowns", "slippage", "slow",
    "slowdown", "slowdowns", "slowed", "slower", "slowest", "slowing",
    "slowly", "slows", "slump", "slumped", "slumping", "slumps",
    "stagnant", "stagnate", "stagnated", "stagnates", "stagnating",
    "stagnation", "strain", "strained", "strains", "stress", "stressed",
    "stresses", "stressful", "stressing", "subpoena", "subpoenaed",
    "subpoenas", "sue", "sued", "sues", "suffer", "suffered",
    "suffering", "suffers", "suing", "susceptibility", "susceptible",
    "suspect", "suspected", "suspects", "suspend", "suspended",
    "suspending", "suspends", "suspension", "suspensions", "suspicious",
    "terminate", "terminated", "terminates", "terminating", "termination",
    "terminations", "threat", "threaten", "threatened", "threatening",
    "threatens", "threats", "tighten", "tightened", "tightening",
    "trouble", "troubled", "troubles", "troublesome", "troubling",
    "unable", "unacceptable", "unacceptably", "unanticipated",
    "unauthorized", "uncertain", "uncertainly", "uncertainty",
    "undermine", "undermined", "undermines", "undermining",
    "underperform", "underperformance", "underperformed",
    "underperforming", "underperforms", "undesirable", "undisclosed",
    "unfair", "unfairly", "unfavorable", "unfavorably", "unfit",
    "unfortunate", "unfortunately", "unlawful", "unlawfully",
    "unpaid", "unprecedented", "unpredictable", "unpredictably",
    "unprofitable", "unreasonable", "unreasonably", "unrecoverable",
    "unresolved", "unsafe", "unsatisfactory", "unsatisfied",
    "unstable", "unsuccessful", "unsuccessfully", "unsuitable",
    "unsupported", "untimely",
    "violate", "violated", "violates", "violating", "violation",
    "violations", "violator", "violators", "volatile", "volatility",
    "vulnerable", "vulnerability", "vulnerabilities",
    "warn", "warned", "warning", "warnings", "warns", "weak",
    "weaken", "weakened", "weakening", "weakens", "weaker", "weakest",
    "weakness", "weaknesses", "worrisome", "worry", "worrying",
    "worse", "worsen", "worsened", "worsening", "worsens", "worst",
    "worthless", "writedown", "writedowns", "writeoff", "writeoffs",
}

UNCERTAINTY_WORDS = {
    "almost", "ambiguity", "ambiguous", "anticipate", "anticipated",
    "anticipates", "anticipating", "appear", "appeared", "appearing",
    "appears", "approximate", "approximately", "approximation",
    "assume", "assumed", "assumes", "assuming", "assumption",
    "assumptions",
    "believe", "believed", "believes", "believing",
    "cautious", "cautiously", "conceivable", "conceivably",
    "conditional", "conditionally", "conjecture", "contingency",
    "contingent", "could",
    "depend", "depended", "dependent", "depending", "depends",
    "deviate", "deviated", "deviates", "deviating", "deviation",
    "deviations", "doubt", "doubtful", "doubts",
    "estimate", "estimated", "estimates", "estimating", "estimation",
    "estimations", "expect", "expectation", "expectations", "expected",
    "expecting", "expects", "expose", "exposed", "exposure",
    "exposures",
    "fluctuate", "fluctuated", "fluctuates", "fluctuating",
    "fluctuation", "fluctuations", "forecast", "forecasted",
    "forecasting", "forecasts",
    "hesitancy", "hesitant", "hypothetical",
    "imprecise", "imprecision", "improbable", "inadvertent",
    "inadvertently", "incompleteness", "indefinite", "indefinitely",
    "indeterminate", "inexact",
    "likelihood", "likely",
    "may", "maybe", "might",
    "nearly", "nonassessable",
    "occasionally", "ordinarily",
    "pending", "perceive", "perceived", "perhaps", "possibility",
    "possible", "possibly", "potential", "potentially", "precaution",
    "precautionary", "precautions", "predict", "predictability",
    "predicted", "predicting", "prediction", "predictions", "predicts",
    "preliminary", "presumably", "presume", "presumed", "presumes",
    "presuming", "presumption", "presumptions", "probabilistic",
    "probabilities", "probability", "probable", "probably", "project",
    "projected", "projecting", "projection", "projections", "projects",
    "prospect", "prospective", "prospects",
    "random", "randomly", "reassess", "reassessed", "reassessing",
    "reassessment", "reconsider", "reconsidered", "reconsidering",
    "reconsideration", "roughly", "rumor", "rumored", "rumors",
    "seem", "seemed", "seeming", "seemingly", "seems", "sometime",
    "sometimes", "somewhat", "somewhere", "speculate", "speculated",
    "speculates", "speculating", "speculation", "speculations",
    "speculative", "suggest", "suggested", "suggesting", "suggestion",
    "suggestions", "suggests", "susceptibility", "susceptible",
    "tend", "tended", "tendency", "tendencies", "tends", "tentative",
    "tentatively",
    "uncertain", "uncertainly", "uncertainties", "uncertainty",
    "unclear", "unconfirmed", "undecided", "undefined",
    "undetermined", "unforeseeable", "unforeseen", "unknown",
    "unlikely", "unplanned", "unpredictable", "unpredictably",
    "unproven", "unquantifiable", "unresolved", "unsettled",
    "unspecified", "untested",
    "vagaries", "vague", "vaguely", "vagueness", "variability",
    "variable", "variables", "variation", "variations", "vary",
    "varied", "varies", "varying", "volatile", "volatility",
}

LITIGIOUS_WORDS = {
    "adjudicate", "adjudicated", "adjudicates", "adjudicating",
    "adjudication", "allegation", "allegations", "allege", "alleged",
    "allegedly", "alleges", "alleging", "amicus", "appeal", "appealed",
    "appealing", "appeals", "appellate", "arbitral", "arbitrate",
    "arbitrated", "arbitrates", "arbitrating", "arbitration",
    "arbitrations", "arbitrator", "arbitrators",
    "claimant", "claimants", "class action", "complainant",
    "complainants", "complaint", "complaints", "consent decree",
    "convict", "convicted", "convicting", "conviction", "convictions",
    "counterclaim", "counterclaims", "court", "courts", "crime",
    "crimes", "criminal", "criminally",
    "decree", "decrees", "defendant", "defendants", "deposition",
    "depositions", "discovery", "docket",
    "felony", "fraud", "frauds", "fraudulent", "fraudulently",
    "grand jury", "guilty",
    "indemnification", "indemnified", "indemnify", "indemnifying",
    "indemnity", "indict", "indicted", "indicting", "indictment",
    "indictments", "infraction", "infractions", "injunction",
    "injunctions", "injury",
    "judge", "judges", "judgment", "judgments", "judicial",
    "jurisdiction", "jurisdictions", "juror", "jurors", "jury",
    "lawsuit", "lawsuits", "legal", "legally", "litigant", "litigants",
    "litigate", "litigated", "litigates", "litigating", "litigation",
    "litigations",
    "magistrate", "mediate", "mediated", "mediates", "mediating",
    "mediation", "mediator", "mediators", "misdemeanor", "misdemeanors",
    "mistrial",
    "notarize", "notarized", "notary",
    "offend", "offended", "offender", "offenders", "offending",
    "patent", "patents", "penalty", "penalties", "perjury",
    "petition", "petitioned", "petitioner", "petitioning", "petitions",
    "plaintiff", "plaintiffs", "plea", "plead", "pleaded", "pleading",
    "pleadings", "pleads", "pleas", "pled", "precedent", "precedents",
    "prejudice", "prejudiced", "prejudices", "prejudicial",
    "proceeding", "proceedings", "prosecute", "prosecuted",
    "prosecutes", "prosecuting", "prosecution", "prosecutions",
    "prosecutor", "prosecutors", "punitive",
    "racketeering", "ruling", "rulings",
    "sanction", "sanctioned", "sanctioning", "sanctions", "sentence",
    "sentenced", "sentences", "sentencing", "settlement", "settlements",
    "settling", "statute", "statutes", "statutory", "subpoena",
    "subpoenaed", "subpoenas", "sue", "sued", "sues", "suit",
    "suits", "suing", "summon", "summoned", "summoning", "summons",
    "testify", "testified", "testifies", "testifying", "testimony",
    "tort", "torts", "trial", "trials", "tribunal", "tribunals",
    "verdict", "verdicts", "violate", "violated", "violates",
    "violating", "violation", "violations", "violator", "violators",
    "warrant", "warrants", "witness", "witnesses",
}

CONSTRAINING_WORDS = {
    "abide", "abiding", "bind", "binding", "bound",
    "cap", "capped", "capping", "caps", "cease", "ceased", "ceases",
    "ceasing", "compel", "compelled", "compelling", "compels",
    "comply", "complied", "complies", "complying", "compliance",
    "condition", "conditional", "conditionally", "conditions",
    "confine", "confined", "confines", "confining", "consent",
    "consented", "consenting", "constrain", "constrained",
    "constraining", "constrains", "constraint", "constraints",
    "contingent", "contractual", "contractually", "curb", "curbed",
    "curbing", "curbs",
    "curtail", "curtailed", "curtailing", "curtailment", "curtails",
    "debar", "debarment", "debarred", "debarring", "decree",
    "decreed", "decreeing", "decrees",
    "forbid", "forbidden", "forbidding", "forbids", "force",
    "forced", "forces", "forcing",
    "impede", "impeded", "impedes", "impeding", "impediment",
    "impediments", "impose", "imposed", "imposes", "imposing",
    "imposition", "inhibit", "inhibited", "inhibiting", "inhibits",
    "injunction",
    "limit", "limitation", "limitations", "limited", "limiting",
    "limits",
    "mandate", "mandated", "mandates", "mandating", "mandatory",
    "must",
    "necessitate", "necessitated", "necessitates", "necessitating",
    "noncompliance",
    "obligate", "obligated", "obligates", "obligating", "obligation",
    "obligations", "obligatory",
    "preclude", "precluded", "precludes", "precluding", "precondition",
    "prerequisite", "prescribe", "prescribed", "prescribes",
    "prescribing", "prescription", "prevent", "prevented", "preventing",
    "prevents", "prohibit", "prohibited", "prohibiting", "prohibition",
    "prohibitions", "prohibitive", "prohibitively", "prohibits",
    "proscribe", "proscribed", "proscribes", "proscribing",
    "proscription",
    "refrain", "refraining", "refrains", "require", "required",
    "requirement", "requirements", "requires", "requiring",
    "restrain", "restrained", "restraining", "restrains", "restraint",
    "restraints", "restrict", "restricted", "restricting",
    "restriction", "restrictions", "restrictive", "restricts",
    "shall",
}
